ignore:
  - "src/debug/*"
  - "*/debug/*"
  - "src/*/deprecated"
  - "src/*/*/deprecated"
  - "src/DataType/Params/deprecated/*"
  - "src/*/temp"
  - "src/*/backup/*"
  - "src/clang/*"
  - "src/standalone/*"
